### ISSUE TITLE
Use save.properties from pwd as default value

### ISSUE THREAD

**Issue by petertrr** [cqfn/save#125]
When `save-cli` is built from a9362a66, and directory structure is as follows:
```
$ ls
save save.properties save.toml tests
```
and save is executed as `./save`, it doesn't read `save.proeprties`, but should, according to the default value

**Comment by kgevorkyan** [comment]
Previously we didn't consider default values for config options at all in course of work of SAVE, because
in SaveProperties was the following logic:
```kotlin
parser.parse(args)
this.testConfigPath = testConfigPath
this.parallelMode = parallelMode
...
```
and this logic overwrites all default values by `null` if they weren't provided in CLI, this is how parser works.
Default values worked only in `performaAnalysisTest`, since we created instance manually without nulls.

We also can't change this logic to something like this (overwrite values only if corresponding field from CLI != `null`)
```kotlin
testConfigPath?.let { this.testConfigPath = testConfigPath }
```
because in this case we won't be able to identify in `mergeConfigWithPriorityToThis()` whether the value was passed by user, or taken from default (situation like for default values in plugin configs)

It was decided to make all fields in SaveProperties `null` by default and to create some instance with explicit values.
So process of merging will be as following:
```kotlin
defaultSavePropertiesInstanse = SaveProperties(testConfigPath = "save.toml", parallelMode = false, ....)
....
....
// Merging:
testConfigPath = testConfigPath ?: configFromPropertiesFile.testConfigPath ?: defaultSavePropertiesInstanse.testConfigPath
```
