### ISSUE TITLE
Delete binaries in integrational tests after all tests are finished 

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/save#208]
Now I am not deleting `ktlint` and `diktat` after the execution of tests

**Comment by akuleshov7** [comment]
it could be a gradle task

**Comment by petertrr** [comment]
> it could be a gradle task

If we make cleanup in gradle task, then gradle should also be responsible for resources downloading, otherwise it just overcomplicates and mixes responsibilities. I tried to use `AfterClass`/`BeforeClass` (which apparently are available for JVM and Native) in #216. I believe it's failing now, because JVM and native tests are deleting resources of each other. So the solution should be either to move everything into gradle or to run tests in temporary directories, one per platform and test class. I personally prefer the latter.
